version: '3.8'

services:
  pokemon-api:
    build: .
    container_name: pokemon-api
    restart: unless-stopped
    ports:
      - "20275:20275"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20275/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory if you want persistent logs
      - ./logs:/app/logs
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge
