# Using compose-spec v2 (no version key)

services:
  pokemon-api:
    image: mateuszg541/pokemon-api-service:latest
    container_name: pokemon-api
    restart: unless-stopped
    ports:
      - "20275:3001"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - pokemon-network
    # Security: Run as non-root user
    user: "1000:1000"
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  pokemon-network:
    driver: bridge
